import PDFDocument from "pdfkit";
import type { Invoice, Bill } from "@sqb/domain-types";

const FONT_SIZE_TITLE = 18;
const FONT_SIZE_HEADING = 12;
const FONT_SIZE_BODY = 10;
const FONT_SIZE_SMALL = 8;
const MARGIN = 50;
const PAGE_WIDTH = 595.28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatMoney(value: string) {
    const parts = value.split(".");
    const intPart = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    return `${intPart}.${parts[1] ?? "00"} UZS`;
}

function drawHeader(doc: PDFKit.PDFDocument, docType: "INVOICE" | "BILL", number: string, issueDate?: string, dueDate?: string) {
    doc.fontSize(FONT_SIZE_TITLE).font("Helvetica-Bold").text(docType, MARGIN, MARGIN);
    doc.fontSize(FONT_SIZE_HEADING).font("Helvetica").text(`#${number}`, MARGIN, MARGIN + 22);

    const rightX = MARGIN + CONTENT_WIDTH - 150;
    doc.fontSize(FONT_SIZE_BODY).font("Helvetica");
    if (issueDate) {
        doc.text(`Issue Date: ${issueDate}`, rightX, MARGIN, { width: 150, align: "right" });
    }
    if (dueDate) {
        doc.text(`Due Date: ${dueDate}`, rightX, MARGIN + 14, { width: 150, align: "right" });
    }

    doc.moveTo(MARGIN, MARGIN + 45).lineTo(MARGIN + CONTENT_WIDTH, MARGIN + 45).stroke();
}

function drawCounterparty(doc: PDFKit.PDFDocument, label: string, name: string, y: number) {
    doc.fontSize(FONT_SIZE_SMALL).font("Helvetica").fillColor("#666666").text(label, MARGIN, y);
    doc.fontSize(FONT_SIZE_BODY).font("Helvetica-Bold").fillColor("#000000").text(name, MARGIN, y + 12);
    return y + 30;
}

function drawLineItemsTable(
    doc: PDFKit.PDFDocument,
    lines: Array<{ description: string; quantity: string; unitPrice: string; taxRate: string; lineTotal: string }>,
    y: number
) {
    const colWidths = [CONTENT_WIDTH * 0.4, CONTENT_WIDTH * 0.12, CONTENT_WIDTH * 0.18, CONTENT_WIDTH * 0.12, CONTENT_WIDTH * 0.18];
    const headers = ["Description", "Qty", "Unit Price", "Tax %", "Total"];

    doc.fontSize(FONT_SIZE_SMALL).font("Helvetica-Bold").fillColor("#444444");
    let x = MARGIN;
    for (let i = 0; i < headers.length; i++) {
        doc.text(headers[i], x, y, { width: colWidths[i], align: i >= 1 ? "right" : "left" });
        x += colWidths[i];
    }

    y += 16;
    doc.moveTo(MARGIN, y).lineTo(MARGIN + CONTENT_WIDTH, y).lineWidth(0.5).stroke();
    y += 6;

    doc.font("Helvetica").fillColor("#000000").fontSize(FONT_SIZE_BODY);
    for (const line of lines) {
        x = MARGIN;
        const values = [line.description, line.quantity, formatMoney(line.unitPrice), `${line.taxRate}%`, formatMoney(line.lineTotal)];
        for (let i = 0; i < values.length; i++) {
            doc.text(values[i], x, y, { width: colWidths[i], align: i >= 1 ? "right" : "left" });
            x += colWidths[i];
        }
        y += 16;

        if (y > 720) {
            doc.addPage();
            y = MARGIN;
        }
    }

    return y;
}

function drawTotals(
    doc: PDFKit.PDFDocument,
    subtotal: string,
    taxTotal: string,
    total: string,
    outstandingLabel: string,
    outstandingValue: string,
    y: number
) {
    y += 10;
    doc.moveTo(MARGIN, y).lineTo(MARGIN + CONTENT_WIDTH, y).lineWidth(0.5).stroke();
    y += 10;

    const labelX = MARGIN + CONTENT_WIDTH - 220;
    const valueX = MARGIN + CONTENT_WIDTH - 110;

    doc.fontSize(FONT_SIZE_BODY).font("Helvetica");
    doc.text("Subtotal:", labelX, y, { width: 110, align: "right" });
    doc.text(formatMoney(subtotal), valueX, y, { width: 110, align: "right" });
    y += 16;

    doc.text("Tax:", labelX, y, { width: 110, align: "right" });
    doc.text(formatMoney(taxTotal), valueX, y, { width: 110, align: "right" });
    y += 16;

    doc.font("Helvetica-Bold");
    doc.text("Total:", labelX, y, { width: 110, align: "right" });
    doc.text(formatMoney(total), valueX, y, { width: 110, align: "right" });
    y += 20;

    doc.font("Helvetica").fontSize(FONT_SIZE_SMALL).fillColor("#666666");
    doc.text(`${outstandingLabel}: ${formatMoney(outstandingValue)}`, labelX, y, { width: 220, align: "right" });

    return y + 20;
}

function drawFooter(doc: PDFKit.PDFDocument, notes?: string) {
    const y = 740;
    doc.fontSize(FONT_SIZE_SMALL).font("Helvetica").fillColor("#999999");
    doc.text("Generated by SQB Business OS", MARGIN, y);
    if (notes) {
        doc.fillColor("#666666").text(`Notes: ${notes}`, MARGIN, y + 12, { width: CONTENT_WIDTH });
    }
}

export function generateInvoicePdf(invoice: Invoice): PDFKit.PDFDocument {
    const doc = new PDFDocument({ size: "A4", margin: MARGIN });

    drawHeader(doc, "INVOICE", invoice.number, invoice.issueDate, invoice.dueDate);
    let y = drawCounterparty(doc, "BILL TO", invoice.counterpartyName, MARGIN + 55);

    y = drawLineItemsTable(
        doc,
        invoice.lines.map((line) => ({
            description: line.description,
            quantity: line.quantity,
            unitPrice: line.unitPrice,
            taxRate: line.taxRate,
            lineTotal: line.lineTotal
        })),
        y + 10
    );

    drawTotals(doc, invoice.subtotal, invoice.taxTotal, invoice.total, "Outstanding", invoice.outstandingTotal, y);
    drawFooter(doc, invoice.notes);

    doc.end();
    return doc;
}

export function generateBillPdf(bill: Bill): PDFKit.PDFDocument {
    const doc = new PDFDocument({ size: "A4", margin: MARGIN });

    drawHeader(doc, "BILL", bill.number, bill.issueDate, bill.dueDate);
    let y = drawCounterparty(doc, "FROM SUPPLIER", bill.counterpartyName, MARGIN + 55);

    y = drawLineItemsTable(
        doc,
        bill.lines.map((line) => ({
            description: line.description,
            quantity: line.quantity,
            unitPrice: line.unitPrice,
            taxRate: line.taxRate,
            lineTotal: line.lineTotal
        })),
        y + 10
    );

    drawTotals(doc, bill.subtotal, bill.taxTotal, bill.total, "Outstanding", bill.outstandingTotal, y);
    drawFooter(doc, bill.notes);

    doc.end();
    return doc;
}
